name: Cat Litter AI Inference
version: "1.0.0"
description: 猫砂盆视觉判断AI推理服务
slug: cat_litter_ai_inference
init: false
arch:
  - amd64
  - aarch64
url: https://github.com/lzg134679/cat-litter-ai-inference
startup: application
boot: auto
environment:
  TZ: "{{ timezone }}"
  PORT: "5555"
ports:
  5555/tcp: 5555
